### ISSUE TITLE
Remove hardcoded taxonomy terms and replace with customizable list of links

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/ohana-web-search#486]
Currently, the entire OpenEligibility taxonomy is hardcoded and displayed when no search results are found. There are two problems with this:
1. It assumes that the API will be using the OE taxonomy, which is not a valid assumption.
2. It assumes that each OE category has been assigned to at least one Service, which is also not a valid assumption.

Instead, when no search results are found, the entity that is deploying the app should be able to decide which links appear there, if any, and where they point to. For example, they could point to a keyword search or a category search.

I propose adding a new setting in settings.yml that looks something like this:

```
links_for_no_results:
  type_of_search: keyword | category
  links:
    - Emergency Food
    - Help Pay Rent
```

The idea is not to have a gazillion links, just the ones that are the most important for the community.
