### ISSUE TITLE
Cassettes have wrong test URL and can't be regenerated

### ISSUE THREAD

**Issue by anselmbradford** [codeforamerica/ohana-web-search#592]
https://github.com/codeforamerica/ohana-web-search/blob/master/spec/support/features/session_helpers.rb#L27

Looks like it should use `/locations/san-maceo-agency` instead of `/locations/sanmaceo-example-agency/san-maceo-agency`, as the former is a 404 on https://ohana-api-test.herokuapp.com/api/locations/sanmaceo-example-agency/san-maceo-agency

https://github.com/codeforamerica/ohana-web-search/blob/master/spec/features/search/results_page_search_spec.rb#L15 Does not look like the right URL either.

Additionally, https://github.com/codeforamerica/ohana-web-search/blob/master/config/application.example.yml#L97 doesn't have the `https://` endpoint, which I think it needs? 

When regenerating the cassettes a large number fail and have a 301 response header. It looks like VCR is visiting `http:` instead of `https:`, which I suspect is the issue.

To repeat:
- Throw out a cassette, such as https://github.com/codeforamerica/ohana-web-search/blob/master/spec/cassettes/address_formatting/when_no_address_elements_are_present/does_not_include_a_Google_Maps_directions_link.yml
- Run `script/test`
- See that generated cassette contains a 301 response and http and https calls:

```

---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/locations/location-with-no-phone
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 301
      message: Moved Permanently
    headers:
      Connection:
      - keep-alive
      Content-Type:
      - text/html
      Transfer-Encoding:
      - chunked
      Status:
      - 301 Moved Permanently
      Location:
      - https://ohana-api-test.herokuapp.com/api/locations/location-with-no-phone
      X-Powered-By:
      - Phusion Passenger 4.0.50
      Date:
      - Tue, 09 Sep 2014 13:47:38 GMT
      Server:
      - nginx/1.6.1 + Phusion Passenger 4.0.50
      Via:
      - 1.1 vegur
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 09 Sep 2014 13:47:38 GMT
recorded_with: VCR 2.9.2
```
